trigger: none

pr:
  branches:
    include:
      - main

pool:
  name: Self-Hosted   # Your aget pool name

stages:
  - stage: CaptureRollbackScripts
    displayName: 'Capture Rollback Scripts and Insert into Mapper Table'
    jobs:
      - job: InsertRollbackScripts
        steps:
          - checkout: self
            persistCredentials: true
          - task: PowerShell@2
            displayName: 'Insert rollback script names into DB'
            inputs:
              targetType: 'inline'
              script: |
                $prId = "$(System.PullRequest.PullRequestId)"
                if (-not $prId) {
                  Write-Warning "No PR ID detected. Using 'local' as PR ID."
                  $prId = "local"
                } else {
                  Write-Host "PR ID detected: $prId"
                }
                $buildId = "$(Build.BuildId)"
                $repoUrl = 'https://github.com/ktsreddy007/DB_Migrotron'
                $repoFolder = 'rollback_sql'
                $targetBranch = "origin/main"
                git fetch origin main
                $sourceBranch = "$(Build.SourceBranchName)"
                if (-not $sourceBranch) {
                  Write-Error "Source branch name not found. Exiting."
                  exit 1
                }
                Write-Host "Source branch: $sourceBranch"
                $changedFiles = git diff --name-only $targetBranch $sourceBranch
                if (-not $changedFiles) {
                  Write-Host "No changed files detected. Exiting."
                  exit 0
                }

                $rollbackScripts = @()
                foreach ($file in $changedFiles) {
                  if ($file -like "rollback_sql/*.sql") {
                    $filename = [System.IO.Path]::GetFileName($file)
                    $rollbackScripts += $filename
                    Write-Host "Detected rollback script: $filename"
                  }
                }
                if ($rollbackScripts.Count -eq 0) {
                  Write-Host "No rollback scripts detected in changes. Exiting."
                  exit 0
                }
                $connectionString = "Server=localhost;Database=Payroll;User Id=$(dbUser);Password=$(dbPassword);"
                $connection = New-Object System.Data.SqlClient.SqlConnection
                $connection.ConnectionString = $connectionString
                $connection.Open()
                foreach ($script in $rollbackScripts) {
                  $query = "INSERT INTO migration_rollback_mapper (rollback_script_name, rollback_script_repo_folder, rollback_script_repo_url, build_id, pr_id) VALUES ('$script', '$repoFolder', '$repoUrl', '$buildId', '$prId')"
                  $command = $connection.CreateCommand()
                  $command.CommandText = $query
                  $command.ExecuteNonQuery()
                  Write-Host "Inserted into DB: $script"
                }
                $connection.Close()
            env:
              dbUser: $(dbUser)
              dbPassword: $(dbPassword)