trigger: none
pr:
  branches:
    include:
      - main
pool:
  name: Self-Hosted   # Your agent pool name

stages:
  - stage: ValidateMigration
    displayName: 'Flyway Migration Validation (Windows Agent)'
    jobs:
      - job: EnsureTools
        displayName: 'Ensure Java and Flyway Installed'
        pool:
          name: Self-hosted
          demands:
            - Agent.OS -equals Windows_NT
        steps:
          - checkout: none

           # ✅ Check and Install Java (if not found)
          - task: PowerShell@2
            displayName: 'Check and Install Java (any version)'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Checking Java installation..."
                try {
                  & java -version > $null 2>&1
                  if ($LASTEXITCODE -eq 0) {
                    Write-Host "✅ Java is already installed."
                  } else {
                    throw "Java not found."
                  }
                } catch {
                  Write-Host "❌ Java not found. Installing OpenJDK 11..."
                  choco install -y openjdk11
                }

          # ✅ Check and Install Flyway CLI (if not found)
          - task: PowerShell@2
            displayName: 'Check and Install Flyway CLI (any version)'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Checking Flyway CLI..."
                try {
                  & flyway -v > $null 2>&1
                  if ($LASTEXITCODE -eq 0) {
                    Write-Host "✅ Flyway CLI is already installed."
                  } else {
                    throw "Flyway not found."
                  }
                } catch {
                  Write-Host "❌ Flyway not found. Installing Flyway CLI..."
                  $flywayZip = "$(Build.SourcesDirectory)\flyway.zip"
                  Invoke-WebRequest -Uri "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.8.1/flyway-commandline-9.8.1-windows-x64.zip" -OutFile $flywayZip
                  Expand-Archive -Path $flywayZip -DestinationPath "$(Build.SourcesDirectory)\flyway"
                  $flywayPath = "$(Build.SourcesDirectory)\flyway\flyway-9.8.1"
                  $env:Path = "$flywayPath;$env:Path"
                }