trigger:
  branches:
    include:
      - main           # Or your default branch name
  paths:
    include:
      - Database/MSSQL_Server/Dev/**

pool:
  name: Self-hosted   # Your agent pool name

steps:
- script: |
    echo "Running pipeline on Dev folder changes only"
    echo "Agent name: $(Agent.Name)"
  displayName: 'Test script step'