trigger: none
#  branches:
#    include:
#      - main

pr:
  branches:
    include:
     - main
#  paths:
#    include:
#      - Database/MSSQL_Server/Dev/rollback_sql/**
      
pool:
  name: Self-Hosted

steps:
  - script: |
      echo "Running test..."
      echo "Welcome to Azure Pipelines!"
    displayName: 'Print Welcome Message'     
