trigger: none 
#  branches:
#    include:
#      - main

pr: none
#  branches:
#    include:
#     - main
#   paths:
#    include:
#      - Database/MSSQL_Server/Dev/rollback_sql/**
      
pool:
  name: Self-Hosted   
