trigger: 
  branches:
    include:
      - main

pr:
  branches:
    include:
     - main
  paths:
    include:
      - Database/MSSQL_Server/Dev/rollback_sql/**
      
pool:
  name: Self-Hosted   
