name: Flyway Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Flyway migration
        run: |
          flyway -url="jdbc:sqlserver://localhost:1433;databaseName=YourDatabase" `
                 -user=sa `
                 -password=YourPassword `
                 -locations=filesystem:sql `
                 migrate